package api

import (
	"net/http"
	"net/url"
	"time"

	"github.com/raphi011/cbs/ledger"
)

// withMiddleware wraps h in the standard chain. Order (outermost first):
// recover → logging → CORS → screen the request target → handler, so a panic is
// caught after the request is logged and CORS headers are still applied to
// error responses.
func (s *Server) withMiddleware(h http.Handler) http.Handler {
	return s.recoverPanic(s.logRequests(s.cors(s.screenRequestTarget(h))))
}

// screenRequestTarget refuses a URL whose decoded path or query carries a
// control character.
//
// This is the read half of the rule ledger.ValidateText states for writes. A %00
// in a path is decoded into the path parameter and handed to the store as a
// lookup key, and what a request may name is this system's question rather than
// a database's.
//
// It sits here rather than in the domain because a URL-borne identifier passes
// through no domain constructor: it is read straight out of the request and used
// as a key. Identifiers in this system are generated by it (`bank_1`,
// `200.100.001`, `dep_3`) and never contain a control character, so a request
// carrying one cannot name anything, and refusing it at the edge is the same
// answer a lookup would give with none of the guessing about what the store
// would have done with it. Identifiers arriving in a request BODY are validated
// in the domain instead, where they are also stored.
func (s *Server) screenRequestTarget(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// r.URL.Path is already percent-decoded, which is the form the handlers
		// and the store see.
		if err := ledger.ValidateText("path", r.URL.Path); err != nil {
			writeBadRequest(w, err.Error())
			return
		}
		query, err := url.ParseQuery(r.URL.RawQuery)
		if err != nil {
			writeBadRequest(w, "malformed query string")
			return
		}
		for key, values := range query {
			if err := ledger.ValidateText("query parameter name", key); err != nil {
				writeBadRequest(w, err.Error())
				return
			}
			for _, v := range values {
				if err := ledger.ValidateText(key, v); err != nil {
					writeBadRequest(w, err.Error())
					return
				}
			}
		}
		next.ServeHTTP(w, r)
	})
}

// cors allows a browser-based frontend (e.g. a React dev server on a different
// origin) to call the API. For a local learning tool it allows any origin and
// short-circuits preflight requests.
func (s *Server) cors(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// logRequests logs the method, path, status, and duration of each request.
func (s *Server) logRequests(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		rec := &statusRecorder{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(rec, r)
		s.log.Info("request",
			"method", r.Method,
			"path", r.URL.Path,
			"status", rec.status,
			"duration", time.Since(start).String(),
		)
	})
}

// recoverPanic turns a panic in a handler into a 500 response instead of
// crashing the server.
func (s *Server) recoverPanic(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rec := recover(); rec != nil {
				s.log.Error("panic recovered", "error", rec, "path", r.URL.Path)
				writeJSON(w, http.StatusInternalServerError, errorBody{Error: "internal server error"})
			}
		}()
		next.ServeHTTP(w, r)
	})
}

// statusRecorder captures the response status code for logging.
type statusRecorder struct {
	http.ResponseWriter
	status      int
	wroteHeader bool
}

func (r *statusRecorder) WriteHeader(code int) {
	if !r.wroteHeader {
		r.status = code
		r.wroteHeader = true
	}
	r.ResponseWriter.WriteHeader(code)
}
